### ISSUE TITLE
Init POST /login

### ISSUE THREAD

**Issue by buk0vec** [buk0vec/threeohseven#10]
- Should take a username and password
- Validate password hash
- If valid, create and return valid JWT

**Comment by buk0vec** [comment]
Took 1h

**Comment by PeteThePilot** [comment]
the login page estimate was like 2h but it ended up taking like 4h bc I had to figure out how to use CSS along with react and learn mui components

**Comment by buk0vec** [comment]
^ this issue is for login API endpoint, moving comment to login page issue
